---
all:
  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 192.0.2.10
    vector:
      hosts:
        vector-01:
          ansible_host: 192.0.2.20
    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 192.0.2.30
